### ISSUE TITLE
Replace Redhat logo on /partners/ with new version

### ISSUE THREAD

**Issue by mangoamelia** [mangoamelia/Zangief#1]
Logo files attached. Please use media replacement in WP so that the adjustment persists (formatting the logo file to adhere to the same ratio/whitespace as the existing partner logos.

Adding the .svg and .eps versions to Zangief/misc/ for formatting.

![rh_technology_partner_logo_v1_1214clean_rgb](https://cloud.githubusercontent.com/assets/8525107/8416120/5f46f17e-1e58-11e5-96b5-3ad9dd1575c6.png)

**Comment by lawsipan** [comment]
Redhat logo updated.
