### ISSUE TITLE
Remove Honeywell logo and replace with alternate customer logo

### ISSUE THREAD

**Issue by mangoamelia** [mangoamelia/Zangief#2]
Honeywell is no longer a customer so we'll need to replace the logo where it is featured on 3scale.net. This includes - 
- index
- /our-customers/
- /3scale-in-action/

Replacement logo (who we'll use instead of them) is currently TBD

**Comment by mangoamelia** [comment]
Ok, here's the logo to use: https://datafox-data.s3.amazonaws.com/images/cb_1d10b83897c0dacf0b2f872f8606068c.png

(you can feel free to crop the "ask awesomely" small copy out of the logo)

**Comment by lawsipan** [comment]
Honeywell logo replaced with Typeform on all 3 pages.
