### ISSUE TITLE
Changes in header/footer to allow SSL 

### ISSUE THREAD

**Issue by mangoamelia** [mangoamelia/Zangief#3]
our product team has been asking for us to make the website SSL-compliant. As I understand it, this means stripping the `http:` value out of links in the header/footer, so for instance:

If `http://www.3scale.net/wp-content/themes/3scale14/css/3sc-bootstrap.min.css` 

is hard coded in the head, we would need to change it to

`//www.3scale.net/wp-content/themes/3scale14/css/3sc-bootstrap.min.css` 

This is similarly the case for anything that is hard-coded instead of a relative link - relative links should be fine if/when we switch the full site over. 

Please start working on this in the staging environment only.

**Comment by lawsipan** [comment]
Changed all links in header/footer to // instead of http://. Is it just the header/footer or do I need to scour the rest of the pages for links like this?

**Comment by mangoamelia** [comment]
You did this on staging, correct? Not on prod?

**Comment by lawsipan** [comment]
correct.

**Comment by mangoamelia** [comment]
@lawsipan everything else _should_ be ok, since we generally have relative links for all on-page stuff.

**Comment by lawsipan** [comment]
I guess I can research this on my own, but to outside links to 3rd-party pages count as "mixing" security models and therefore break the https?

**Comment by lawsipan** [comment]
Did the research on this, it's only local links that need to be changed to //, 3rd party are good to go.
