### ISSUE TITLE
Blog page featured images vs. text layout

### ISSUE THREAD

**Issue by kristennash** [mangoamelia/Zangief#4]
I’ve been making featured images square with Illustrator, but it would save me a lot of time if instead we change the page to not wrap the text around the bottom.

Example: make them all look like "Building Effective API Programs" rather than the Heroku tutorial. 

<img width="876" alt="screen shot 2015-07-09 at 11 17 34 am" src="https://cloud.githubusercontent.com/assets/4986766/8603329/4ff27b72-262c-11e5-8769-0613aa246dcc.png">

**Comment by mangoamelia** [comment]
@lawsipan to clarify a bit - we basically don't want text excerpts to wrap around the featured image - not sure if this is easier to do by setting a fixed minimum height for the featured image container or if there's a better way to accomplish. Staging environment is freshly updated and ready to use for testing.

**Comment by kristennash** [comment]
@lawsipan I’m not able to add featured images to blog posts anymore. Any idea why this is happening?

**Comment by mangoamelia** [comment]
@lawsipan any progress on this?

**Comment by mangoamelia** [comment]
Issue with adding featured images has been resolved; still waiting on the original fix to prevent text wrap when images are <200px height.

**Comment by lawsipan** [comment]
Fixed. Changed min-height of post-image to 250px, it now prevents wrapping on the archive page.
